Feat/qr scanner
thinc-org/JS-BKK-Front pull request #14
Opened 2020-01-13 09:48 UTC by boompikachu

2020-01-13 10:16 UTC, new5558 requested changes

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
> +      {/* <label className='mt-3 py-2 px-8 bg-gray-800 text-white rounded cursor-pointer'>
remove comments

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
> +      {qrReady ? (
change to qrReady  && <QrReader
          className='w-40 h-40 mt-4 rounded'
          delay={300}
          onError={handleError}
          onScan={handleScan}
        />

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
install prettier and enable vscode set format on save.

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
> +      {/* <label className='mt-3 py-2 px-8 bg-gray-800 text-white rounded cursor-pointer'>
remove this

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
> +// import QrReader from 'react-qr-reader';
remove this

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
> +  const handleScan = (data: string | null) => {
consider using  [useCallback](https://reactjs.org/docs/hooks-reference.html#usecallback)

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
> +  const QrReader = dynamic(() => import('react-qr-reader'), {
consider moving this component outside functional component to avoid rerender

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
> +            setIsOpen(true);
try changing name to setLoginError, loginError

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
> +  const QrReader = dynamic(() => import('react-qr-reader'), {
Also try using react suspense to do [lazyload](https://blog.bitsrc.io/lazy-loading-react-components-with-react-lazy-and-suspense-f05c4cfde10c)

2020-01-13 10:16 UTC, new5558 commented on pages/login/index.tsx
> +  const [isOpen, setIsOpen] = useState(false);
useState<boolean>

2020-01-14 14:43 UTC, hamzaabamboo reviewed
LGTM

2020-01-18 06:08 UTC, boompttn commented on pages/login/index.tsx
> +      {qrReady ? (
&& with what?

2020-01-18 06:08 UTC, boompttn commented on pages/login/index.tsx
> +  const [isOpen, setIsOpen] = useState(false);
What do you mean? it's already useState

2020-01-18 10:53 UTC, new5558 approved these changes

2020-01-18 10:58 UTC, merged